"""Add TokenBlacklist table

Revision ID: 40b7efc84d4f
Revises: 1a2b3c4d5e6f
Create Date: 2026-05-23 13:25:32.959771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b7efc84d4f'
down_revision: Union[str, Sequence[str], None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('Token', sa.String(length=500), nullable=False),
    sa.Column('ExpiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('Token')
    )
    op.create_index(op.f('ix_token_blacklist_Token'), 'token_blacklist', ['Token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_Token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
