"""add_payment_status

Revision ID: a98614fcb7fe
Revises: 1a2b3c4d5e6f
Create Date: 2026-05-22 23:26:10.793466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a98614fcb7fe'
down_revision: Union[str, Sequence[str], None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    payment_status_enum = sa.Enum('Pending', 'Settled', 'Failed', 'Refunded', name='payment_status_enum')
    payment_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('payments', sa.Column('Status', payment_status_enum, server_default='Pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'Status')
    payment_status_enum = sa.Enum('Pending', 'Settled', 'Failed', 'Refunded', name='payment_status_enum')
    payment_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
